Update cpp.yml

diff --git a/.github/workflows/cpp.yml b/.github/workflows/cpp.yml
--- a/.github/workflows/cpp.yml
+++ b/.github/workflows/cpp.yml
@@ -559,12 +559,18 @@ jobs:
         env:
           # We can invalidate the current cache by updating this.
           CACHE_VERSION: "2022-09-13"
-      - name: Install LLVM for Windows ARM64
-        shell: bash
+      - name: Install LLVM for Win-ARM64
+        shell: pwsh
         run: |
-          curl -L -o LLVM-woa64.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.0/LLVM-21.1.0-woa64.exe
-          ./LLVM-woa64.exe /S
-          echo "C:/Program Files/LLVM/bin" >> $GITHUB_PATH
+          Invoke-WebRequest https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.0/LLVM-21.1.0-woa64.exe -UseBasicParsing -OutFile LLVM-woa64.exe
+          $expectedHash = "3f181aecc83d0eb40fb966ce18b97a3602871dbff83fc91745e7e0fd6661a7f7"
+          $fileHash = (Get-FileHash -Path "LLVM-woa64.exe" -Algorithm SHA256).Hash
+          if ($fileHash -ne $expectedHash) {
+              Write-Error "Checksum verification failed. The downloaded file may be corrupted or tampered with."
+              exit 1
+          }
+          Start-Process -FilePath ".\LLVM-woa64.exe" -ArgumentList "/S" -Wait
+          echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
       - name: Build
         shell: cmd
         run: |
